import './globals.css'
import { Public_Sans } from 'next/font/google'
import { Navbar } from '@/components';
import AuthProvider from './AuthProvider';

const defaultFont = Public_Sans({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${defaultFont.className}`}>
        <AuthProvider>
          <Navbar />
          {children}
        </AuthProvider>
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
      </body>
    </html>
  )
}
