import './globals.css'
import { Mulish } from 'next/font/google'
import { Navbar } from '@/components'

const defaultFont = Mulish({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={defaultFont.className}>
        <Navbar />
        {children}
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
      </body>
    </html>
  )
}
